# Generated by Django 5.2 on 2025-04-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_alter_user_is_student_alter_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='Asia/Tashkent', max_length=100),
            preserve_default=False,
        ),
    ]
