# Generated by Django 5.2 on 2025-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_student_phone_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='descreptions',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
