# Generated by Django 5.2 on 2025-04-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0007_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='excused_students',
            field=models.ManyToManyField(related_name='excused', to='configapp.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_students',
            field=models.ManyToManyField(related_name='attended', to='configapp.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('registered', "Ro'yxatdan o'tgan"), ('studying', "O'qiyotgan"), ('graduated', 'Bitirib ketgan')], default='registered', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(related_name='get_teachers', to='configapp.groupstudent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='get_student', to='configapp.groupstudent'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.groupstudent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configapp.lesson'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.student')),
            ],
        ),
    ]
