# Generated by Django 5.2 on 2025-05-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0009_attendance_date_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudent',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='departments',
        ),
    ]
