# Generated by Django 5.2 on 2025-05-04 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0010_remove_groupstudent_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(max_length=500, related_name='get_teachers', to='configapp.groupstudent'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
