# Generated by Django 5.2 on 2025-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0011_alter_teacher_groups_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(related_name='get_department', to='configapp.departments'),
        ),
    ]
