# Generated by Django 5.2 on 2025-05-05 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0012_teacher_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='departments',
        ),
        migrations.AddField(
            model_name='departments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
